onlyBuiltDependencies:
  - ' '
  - '"'
  - ','
  - /
  - '@'
  - '['
  - ']'
  - a
  - b
  - d
  - e
  - esbuild
  - h
  - i
  - j
  - k
  - l
  - m
  - o
  - p
  - r
  - s
  - sharp
  - u
  - unrs-resolver
  - w
