# Trivy Secret Scanning Configuration
# Detects secrets, API keys, passwords in source code

rules:
  # AWS
  - id: aws-access-key-id
    category: AWS
    title: AWS Access Key ID
    severity: CRITICAL
    regex: 'AKIA[0-9A-Z]{16}'

  - id: aws-secret-access-key
    category: AWS
    title: AWS Secret Access Key
    severity: CRITICAL
    regex: '(?i)aws(.{0,20})?(?-i)[''"][0-9a-zA-Z/+]{40}[''"]'

  # Database credentials
  - id: database-password
    category: Database
    title: Database Password
    severity: HIGH
    regex: '(?i)(postgres|mysql|redis|mongo).*password\s*[=:]\s*[''"]?[^\s''"]{8,}[''"]?'

  # API Keys
  - id: generic-api-key
    category: API
    title: Generic API Key
    severity: HIGH
    regex: '(?i)(api[_-]?key|apikey|api[_-]?secret)\s*[=:]\s*[''"]?[a-zA-Z0-9_-]{20,}[''"]?'

  # JWT Secrets
  - id: jwt-secret
    category: Authentication
    title: JWT Secret
    severity: CRITICAL
    regex: '(?i)(jwt[_-]?secret|secret[_-]?key)\s*[=:]\s*[''"]?[^\s''"]{16,}[''"]?'

  # Private Keys
  - id: private-key
    category: Cryptography
    title: Private Key
    severity: CRITICAL
    regex: '-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'

  # Keycloak
  - id: keycloak-secret
    category: Authentication
    title: Keycloak Client Secret
    severity: HIGH
    regex: '(?i)keycloak.*secret\s*[=:]\s*[''"]?[a-zA-Z0-9_-]{20,}[''"]?'

# Allowed patterns (false positives)
allow-rules:
  # Example values in documentation
  - id: example-values
    regex: '(example|sample|test|dummy|placeholder)'

  # Environment variable references
  - id: env-vars
    regex: '\$\{?[A-Z_]+\}?'

# Paths to skip
skip-paths:
  - '**/test/**'
  - '**/tests/**'
  - '**/__tests__/**'
  - '**/fixtures/**'
  - '**/mocks/**'
  - '**/*.test.*'
  - '**/*.spec.*'
  - '**/node_modules/**'
  - '**/.git/**'
